BigInt-opt
FedosOnGIT/first-term pull request #1
Opened 2020-10-06 20:30 UTC by FedosOnGIT

2020-10-09 12:11 UTC, kt-cpp requested changes
Тут смотрелся только оптимизированный вектор

2020-10-09 12:11 UTC, kt-cpp commented on bigint-optimized/big_integer_testing.cpp
> -
Зачем ты удалил тесты?

2020-10-09 12:11 UTC, kt-cpp commented on bigint-optimized/buffer.h
> +    }
Вектор прекрасно справляется сам это сделать

2020-10-09 12:11 UTC, kt-cpp commented on bigint-optimized/small-object-vector.h
> +    static const size_t MAX = 5;
`constexpr`

2020-10-09 12:11 UTC, kt-cpp commented on bigint-optimized/small-object-vector.h
> +        if (*this != &other) {
Это условие проверяет не то, что тут нужно

2020-10-09 12:11 UTC, kt-cpp commented on bigint-optimized/small-object-vector.h
> +    bool will_grow;
Из названия переменной не очевидно какой именно смысл она несёт

2020-10-09 12:11 UTC, kt-cpp commented on bigint-optimized/small-object-vector.h
> +        }
Почему тут смотрят на `second.big`, если по смыслу он в состоянии small?

2020-10-09 12:11 UTC, kt-cpp commented on bigint-optimized/small-object-vector.h
> +            new (&big)copy_vector<T>(data);
Тут происходит лишнее копирование вектора, которое можно избежать, сделав твоему `copy_vector` конструктор от двух указателей как у обычного вектора

2020-10-09 12:11 UTC, kt-cpp commented on bigint-optimized/small-object-vector.h
> +            new (&big)copy_vector<T>(data);
А ещё сейчас при исключении в конструкторе `copy_vecor` у тебя все функции, вызывающие `convert_small_to_big` лишатся строгой гарантии исключений ибо ты вызываешь деструкторы до того как безопасно скопируешь все элементы

2020-10-09 12:11 UTC, kt-cpp commented on bigint-optimized/small-object-vector.h
> +    }
Этот метод может иметь строгую гарантию исключений, но у тебя не имеет из-за  `convert_small_to_big`

2020-10-09 12:11 UTC, kt-cpp commented on bigint-optimized/small-object-vector.h
> +    }
Эта функция точно делает что должна?

2020-10-09 12:11 UTC, kt-cpp commented on bigint-optimized/small-object-vector.h
> +        }
* В целом `i` не нужен и можно обойтись лишь `position`
* Эта функция и все, кто её вызывают лишены строгой гарантии исключений если `size != 0`, ибо ты вызываешь деструкторы до того как безопасно скопировал элементы

2020-10-09 12:11 UTC, kt-cpp commented on bigint-optimized/small-object-vector.h
> +    void allocate(size_t length, const T& element) {
Эта функция нигде не используется

2020-10-09 12:11 UTC, kt-cpp commented on bigint-optimized/small-object-vector.h
> +            }
Этим кодом ты не добился никаких гарантий, а лишь сделал лишние копии

2020-10-09 12:11 UTC, kt-cpp commented on bigint-optimized/small-object-vector.h
> +    void clear(size_t number) {
Мб стоит её назвать clear_small судя по коду функции?

2020-10-09 12:11 UTC, kt-cpp commented on bigint-optimized/small-object-vector.h
> +    }
Этот метод может иметь строгую гарантию исключений, но не имеет

2020-10-09 12:11 UTC, kt-cpp commented on bigint-optimized/small-object-vector.h
> +    }
Лучше сделать `using std::swap`, чтобы подтянуть потенциально особые свопы через adl, нежели явно звать только стдшный всегда

2020-10-09 16:26 UTC, FedosOnGIT commented on bigint-optimized/small-object-vector.h
> +    }
Всё исправил!

2020-10-09 19:46 UTC, kt-cpp commented on bigint-optimized/small-object-vector.h
> +    bool will_grow;
Формально, из того что вектор сейчас в сосоянии small не значит что он вырастет. Плюс это всё ещё слишком сложный способ сказать `is_small`, что требует на 1 цепочку ассоциаций меньше для понимания

2020-10-09 20:07 UTC, kt-cpp requested changes
А ещё ответил в старые треды

2020-10-09 20:07 UTC, kt-cpp commented on bigint-optimized/small-object-vector.h
> +            new (&big)copy_vector<T>(main);
Лишнее копирование вектора

2020-10-09 20:07 UTC, kt-cpp commented on bigint-optimized/small-object-vector.h
> +                std::swap(small[i],small[size - i - 1]);
`std::reverse`?

2020-10-09 20:07 UTC, kt-cpp commented on bigint-optimized/small-object-vector.h
> +            clear_small(size);
И зачем тут уничтожать элементы?

2020-10-09 20:08 UTC, kt-cpp commented on bigint-optimized/small-object-vector.h
> +    }
Нужно занести в скоуп одной данной функции, а не всего файла

2020-10-09 20:08 UTC, kt-cpp commented on bigint-optimized/small-object-vector.h
> +    }
Всё ещё не имеет

2020-10-09 20:08 UTC, kt-cpp commented on bigint-optimized/small-object-vector.h
> +    }
Можно без ребячества?

2020-10-09 20:09 UTC, kt-cpp commented on bigint-optimized/big_integer_testing.cpp
> -
Всё ещё не вернул плюс перенос в конец файла

2020-10-09 20:10 UTC, kt-cpp commented on bigint-optimized/small-object-vector.h
> +            new (&big)copy_vector<T>(data);
Всё ещё не имеет

2020-10-09 20:11 UTC, kt-cpp commented on bigint-optimized/small-object-vector.h
> +    }
Всё ещё не имеет по транзитивностю, плюс сейчас не изменяет азмер

2020-10-10 00:00 UTC, FedosOnGIT commented on bigint-optimized/big_integer_testing.cpp
> -
вернул

2020-10-10 00:01 UTC, FedosOnGIT commented on bigint-optimized/small-object-vector.h
> +    bool will_grow;
но есть вероятность, мне просто нравится это имя!

2020-10-12 10:40 UTC, kt-cpp commented on bigint-optimized/small-object-vector.h
> +    bool will_grow;
Подобный код пишется не для себя, а для прочтения его другими людьми

2020-10-12 10:42 UTC, kt-cpp commented on bigint-optimized/small-object-vector.h
> +    }
Кажется подобную функция принято называть просто `size`, что к тому же упрощает замену обычного вектора на твой в бигинте

2020-10-12 10:43 UTC, kt-cpp commented on bigint-optimized/small-object-vector.h
> +    }
А ещё почему она как минимум не `const`?

2020-10-12 11:01 UTC, kt-cpp commented on bigint-optimized/small-object-vector.h
> +            new (&big)copy_vector<T>(data);
Уже лучше, но есть вопрос по поводу того, почему эта функция как-то изменяет размер (т.е. количество элементов), хотя он по факту не меняется. Я вижу как вариант передавать туда **предпологаемый** новый размер вектора, но не изменять его внутри. Либо вообще сказать, что она безусловно переводит тебя в состояние big, и код снаружи уже контролирует когда её вызывать

2020-10-12 11:06 UTC, kt-cpp commented on bigint-optimized/small-object-vector.h
> +            new (&big)copy_vector<T>(data);
Вообще посмотрев на использовние, я считаю тут вообще нельзя изменять размер, ибо это происходит до вызова конструктора нового элемента. Так что если это конструктор кинет исклчение, то деструктор вектора будут уничтожать больше элементов, чем должен

2020-10-12 11:06 UTC, kt-cpp commented on bigint-optimized/small-object-vector.h
> +    }
Отписал про размер в тред выше

2020-10-12 11:29 UTC, kt-cpp requested changes

2020-10-12 11:29 UTC, kt-cpp commented on bigint-optimized/small-object-vector.h
> +    }
Выглядит как это функции нет причины быть `friend` и получать доступ к приватным полям

2020-10-12 11:29 UTC, kt-cpp commented on bigint-optimized/small-object-vector.h
> +    }
А тут вообще перевызыается внешняя функции, так что быть friend нет смысла

2020-10-12 11:29 UTC, kt-cpp commented on bigint-optimized/small-object-vector.h
> +        } else {
А что будет, если вылетит исключение в конструкторе копирования элемента?

2020-10-12 11:29 UTC, kt-cpp commented on bigint-optimized/small-object-vector.h
> +    }
* Почему на 70 строчке делаются изменения с вектором до проверки `this`?
* Если `take_small` кинет исключение, то деструктор вектора потом будет удалять несущестующие элемнеты

2020-10-12 11:29 UTC, kt-cpp commented on bigint-optimized/small-object-vector.h
> +            }
Кажется это тоже `for`

2020-10-14 21:30 UTC, kt-cpp commented on bigint-optimized/small-object-vector.h
> +        } else {
Всё ещё не произойдёт ничего хорошего

2020-10-14 21:38 UTC, kt-cpp requested changes
Плюс старые треды

2020-10-14 21:38 UTC, kt-cpp commented on bigint-optimized/small-object-vector.h
>      }
Присмотревшись я скажу, что тут вообще происходит что-то странное, ибо ты никак не уничтожаешь старые данные. Учитывая, что ты реализовал свап я не вижу причин не сделать всё через своп-трик

2020-10-14 21:38 UTC, kt-cpp commented on bigint-optimized/small-object-vector.h
>      friend void swap(small_object_vector<T> &first, small_object_vector<T> &second) {
Снова как в векторе зачем делать `friend`, нарушая инкапсуляцию, если можно сделать метод у класса, а внешний свап реализовать как `first.swap(second)`

2020-10-15 09:28 UTC, kt-cpp requested changes
Осталась всего одна строчка..

2020-10-15 09:28 UTC, kt-cpp commented on bigint-optimized/small-object-vector.h
>              }
А исключение кто пробросит? Сейчас ты молча его съедаешь, и вызываеющий очень удивится, когда попытается использовать данный вектор

2020-10-16 11:49 UTC, kt-cpp approved these changes

2020-10-16 11:50 UTC, merged