bigint
FedosOnGIT/first-term pull request #3
Opened 2020-10-06 21:32 UTC by FedosOnGIT

2020-10-09 20:20 UTC, kt-cpp requested changes
Менять тесты не разрешалось.

2020-10-09 20:20 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        else { answer.sign = b.sign; }
Тернарник

2020-10-09 20:20 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    return false;
Эту функцию можно написать аккуратнее в один фор

2020-10-09 20:20 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        return a.size < b.size;
эта конструкция пишется без ифа одними логическими (или хотя бы тернарным) операторами

2020-10-09 20:20 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        }
аналогично

2020-10-09 20:20 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        *this *= 10;
Каждый раз 10 кастуется в bigint, сделайте константу

2020-10-09 20:20 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        int64_t two = b.size > i ? b[i] : 0;
Если вы сделаете какой-нибудь safe_get, в этом и многих других местах удастся избежать лишнего кода. Поправьте везде

2020-10-09 20:20 UTC, kt-cpp commented on bigint/big_integer.h
> +    size_t size;
Зачем отдельно size, когда можно bits.size()?

2020-10-09 20:20 UTC, kt-cpp commented on bigint/big_integer_testing.cpp
> -
По какой причине этот тест был удалён и по какой причине вы в принципе трогаете файлы с тестами?

2020-10-09 21:20 UTC, FedosOnGIT commented on bigint/big_integer_testing.cpp
> -
Возможно нечайно удалил, исправлю

2020-10-09 22:19 UTC, FedosOnGIT commented on bigint/big_integer.cpp
> +        *this *= 10;
Только на неё ругаются плюсы!

2020-10-09 22:32 UTC, FedosOnGIT commented on bigint/big_integer.cpp
> +        int64_t two = b.size > i ? b[i] : 0;
Один код заменился другим, но дело сделано!

2020-10-09 23:15 UTC, FedosOnGIT commented on bigint/big_integer_testing.cpp
> -
Сейчас пытаюсь взять этот тест у других людей, но его нет!

2020-10-09 23:27 UTC, FedosOnGIT commented on bigint/big_integer.h
> +    size_t size;
Для 0

2020-10-13 15:37 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        int64_t two = b.size > i ? b[i] : 0;
Почему она сделана как `friend` функция с нарушением инкапсуляции вместо метода класса?

2020-10-13 15:40 UTC, kt-cpp commented on bigint/big_integer.h
> +    size_t size;
Поясни

2020-10-13 15:54 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    return false;
Всё ещё можно сделать аккуратнее и читабельнее

2020-10-13 15:55 UTC, kt-cpp requested changes

2020-10-13 15:55 UTC, kt-cpp commented on bigint/big_integer.cpp
> +const big_integer TEN = 10;
Сделай её `static` ибо ей нет смысла торчать наружу

2020-10-13 18:34 UTC, FedosOnGIT commented on bigint/big_integer.h
> +    size_t size;
при инициализации bigint он должен равняться 0. Я очень много где юзаю push_back для только что инициализированного bigint я должен поменять последний бит а не добавлять в конец. А теперь предположим, что я запушбекал 0, тогда следующий push_back уже должен работать как обычный пушбек, а не замена бита. В этом и проблема

2020-10-14 21:40 UTC, kt-cpp commented on bigint/big_integer.h
> +    size_t size;
Я ничего не понял из твоих слов. Перефразируй пожалуйста

2020-10-14 21:43 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    return false;
Не переписал

2020-10-14 21:47 UTC, kt-cpp requested changes
Старые треды

2020-10-14 21:47 UTC, kt-cpp commented on bigint/big_integer.h
> +    }
Зачем эта функция, учитывая что она каждый раз возвращает копию

2020-10-14 21:47 UTC, kt-cpp commented on bigint/big_integer.cpp
>  big_integer::big_integer(std::string const &str) : sign(false) {
Где обработка ошибок в этом конструкторе. Никто не гарантирует, что всегда дадут корректные строки

2020-10-14 23:42 UTC, FedosOnGIT commented on bigint/big_integer.h
> +    size_t size;
У меня есть функция push_back, если посмотреть по коду, то использую я её довольно часто. Вот собственно она
    void push_back(uint32_t element) {
        if (!size) {
            bits[0] = element;
        } else {
            bits.push_back(element);
        }
        size++;
    }
Для чего она нужна, думаю ясно.
Проблема заключается в следующем: При инициализации bigint он должен равняться 0, значит, если я делаю push_back в только что созданный bigint, то мне надо заменить этот 0 на нужное число (чтобы например 1, не превратился в 10). Кажется что достаточно проверять что bits.size = 1 && bits[0] = 0, но если я сделаю push_back(0), то у меня всё также останется bits.size = 1 bits[0] = 0 и например вместо 10, я получу 1. Я нашёл две идеи, либо можно заифать, но тогда получится много if, либо сделать какую-то переменную, которая покажет, что мы только создали bigint

2020-10-15 09:49 UTC, kt-cpp requested changes
Старые треды

2020-10-15 09:49 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        }
Какое исключение тыт тут собрался кидать? `throw;` кидает наверх только что пойманное исключение, а что-то `catch` я не вижу

2020-10-15 09:49 UTC, kt-cpp commented on bigint/big_integer.cpp
>      *this = 0;
Вместо этого можно было вызвать дефольный конструктор бигинта в блоке инициализации

2020-10-15 09:49 UTC, kt-cpp commented on bigint/big_integer.h
> +    size_t size;
Обсудили в лс, ждём правок или пруфов что не поправить

2020-10-15 09:50 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    return false;
Обсудили в лс, ждём правок или пруфов что не поправить

2020-10-15 16:42 UTC, kt-cpp commented
А ещё у теюя одноврменно существует функция `ten()` и отдельно константа `TEN` в другой функции

2020-10-16 12:51 UTC, kt-cpp requested changes
Обсудили в лс унификацию 0

2020-10-16 13:57 UTC, kt-cpp approved these changes

2020-10-16 13:57 UTC, merged