vector
FedosOnGIT/first-term pull request #4
Opened 2020-10-08 22:07 UTC by FedosOnGIT

2020-10-09 08:24 UTC, kt-cpp requested changes

2020-10-09 08:24 UTC, kt-cpp commented on vector/vector.h
> +    typedef T const *const_iterator;
`using`

2020-10-09 08:24 UTC, kt-cpp commented on vector/vector.h
> +    }
Эта функция не делает, что должна

2020-10-09 08:24 UTC, kt-cpp commented on vector/vector.h
> +        size_t position = pos - data_;
`ptrdiff_t`

2020-10-09 08:24 UTC, kt-cpp commented on vector/vector.h
> +        size_t position = pos - data_;
`ptrdiff_t`

2020-10-09 08:24 UTC, kt-cpp commented on vector/vector.h
> +        size_--;
`pop_back`?

2020-10-09 08:24 UTC, kt-cpp commented on vector/vector.h
> +        size_t end = last - data_;
`ptrdiff_t`

2020-10-09 08:24 UTC, kt-cpp commented on vector/vector.h
> +        return data_ + begin;
`erase` не должен переаллоцировать новый буффер данных ибо это дорого

2020-10-09 08:24 UTC, kt-cpp commented on vector/vector.h
> +    friend void swap(vector<K> &first, vector<K> &second);
Почему мы не сделать метод у класса `.swap`, а во внешней функции его просто перевызвать без всяких друзей?

2020-10-09 08:24 UTC, kt-cpp commented on vector/vector.h
> +    size_t increase_capacity() const {
Имя это функцции не совсем соотвествует тому, что она делает, ибо она не увеличивает вместимость вектор, а лишь возвращает увеличенный размер вместимости

2020-10-09 08:24 UTC, kt-cpp commented on vector/vector.h
> +            }
Казалось бы тебе тут `i` не нужен, и можно использовать везде `postion`

2020-10-09 08:24 UTC, kt-cpp commented on vector/vector.h
> +    static T *increase_buffer(T *data, size_t new_size, size_t old_size) {
Сюда бы ассёрт на то, что новый размер не меньше старого иначе код ниже может быть ub и в дебаге будет неприятно ловить

2020-10-09 08:24 UTC, kt-cpp commented on vector/vector.h
> +    static T *increase_buffer(T *data, size_t new_size, size_t old_size) {
Ну и по смыслу это кажется не `new_size`, а `new_capacity`, судя по коду. В том смысле, что одно - размер буфера, а второе количество данных в нём

2020-10-09 08:24 UTC, kt-cpp commented on vector/vector.h
> +#endif // VECTOR_H
Перенос в конце файла

2020-10-09 19:27 UTC, kt-cpp commented on vector/vector.h
> +#endif // VECTOR_H
Не исправил

2020-10-09 19:28 UTC, kt-cpp requested changes
Ответил ещё в старые треды

2020-10-09 19:28 UTC, kt-cpp commented on vector/vector.h
> +                    position--;
Кажется это называется `for`

2020-10-09 21:24 UTC, FedosOnGIT commented on vector/vector.h
> +                    position--;
Нет, длина new_data может быть больше position

2020-10-12 10:24 UTC, kt-cpp commented on vector/vector.h
> +                    position--;
Это всё ещё `for`

2020-10-12 10:26 UTC, kt-cpp commented on vector/vector.h
> +    friend void swap(vector<K> &first, vector<K> &second);
Всё ещё ждём мотивацию, для предоставления доступа к приатным членам класса, нарушая инкапсуляцию

2020-10-12 10:27 UTC, kt-cpp requested changes
Ещё чуть чуть

2020-10-15 08:56 UTC, kt-cpp approved these changes

2020-10-15 08:56 UTC, merged